name: Build & host at Firebase

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: install NPM & build App
      run: yarn install && npm install -g firebase-tools && cd web && npm run build && npm run export
    - name: upload artifact to Firebase Hosting
      run: cd web && ls && firebase deploy --only hosting --project ${{ secrets.FIREBASE_WEB_ID }} --token ${{ secrets.FIREBASE_TOKEN }}
